using FluentMigrator;

namespace DatabaseMigrator.Migrations;

[Migration(202505111400)]
public class ChangeToIdentityColumns : Migration
{
    public override void Up()
    {
        // Drop sequence defaults
        Execute.Sql(@"
            ALTER TABLE ""Orders"" ALTER COLUMN ""Id"" DROP DEFAULT;
            ALTER TABLE ""OrderItems"" ALTER COLUMN ""Id"" DROP DEFAULT;
            
            -- Recreate tables with IDENTITY columns
            ALTER TABLE ""Orders"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
            ALTER TABLE ""OrderItems"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
            
            -- Drop sequences as they're no longer needed
            DROP SEQUENCE IF EXISTS orders_id_seq;
            DROP SEQUENCE IF EXISTS order_items_id_seq;
        ");
    }

    public override void Down()
    {
        // Revert back to sequence-based auto-increment
        Execute.Sql(@"
            ALTER TABLE ""Orders"" ALTER COLUMN ""Id"" DROP IDENTITY IF EXISTS;
            ALTER TABLE ""OrderItems"" ALTER COLUMN ""Id"" DROP IDENTITY IF EXISTS;
            
            -- Recreate sequences
            CREATE SEQUENCE IF NOT EXISTS orders_id_seq;
            CREATE SEQUENCE IF NOT EXISTS order_items_id_seq;
            
            -- Set defaults back to sequence-based
            ALTER TABLE ""Orders"" ALTER COLUMN ""Id"" SET DEFAULT nextval('orders_id_seq');
            ALTER TABLE ""OrderItems"" ALTER COLUMN ""Id"" SET DEFAULT nextval('order_items_id_seq');
        ");
    }
} 