version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ProcessingOrders.Api/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__OrdersDb=Server=db;Database=OrdersDb;User Id=sa;Password=YourPassword123!;TrustServerCertificate=True;
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - db
    networks:
      - orders-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
    ports:
      - "1433:1433"
    volumes:
      - orders-db-data:/var/opt/mssql
    networks:
      - orders-network

volumes:
  orders-db-data:

networks:
  orders-network:
    driver: bridge 